apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
  namespace: webapps
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHRvaHpqcGJv
  CLOUDINARY_KEY: MzE0MTMzOTE0NTg0NDQ3
  CLOUDINARY_SECRET: U3dUQlc5YktBc0pCNEJsbUhiWXp5R1ZQVHdB
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljblZoYm1FaUxDSmhJam9pWTIxdGFtVnFiSFkwTVRkdWFESnZjR3BuYUdOM09HZzJNQ0o5Lm9QaTc1Q2pjUVY1cjN5SktvUXhKSWc=
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjExMjJAY2x1c3RlcjEuZWdibXVkei5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMQ==
